version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "15 * * * *"   # every 15 minutes
    open-pull-requests-limit: 1
    allow:
      - dependency-name: "flet*"

    groups:
      flet:
        applies-to: version-updates
        versioning-strategy: "increase"
        patterns:
          - "flet*"